### ISSUE TITLE
Development timeline + milestone update/reorganisation

### ISSUE THREAD

**Issue by janbaykara** [david-sabata/web-scrobbler#780]
@david-sabata I think we could use issue milestones to better effect, as they've been under-employed so far. 

I'm sure you have precise feature ideas, and more abstract ambitions about how you see the extension developing in the coming months and years; I'm sure those of us who contribute also have thoughts in the same vein.

There are loads of awesome things we could do with this project, and it'd be great to see everyone's thoughts and ideas shared with the world in writing.

With them assigned to milestones, they could give a focus and direction to feature development; recently we've seen contributors binge-fixing open issues, but I'm sure they'd equally be up to the challenge of building out new features that have been discussed and planned.

If nothing else, I think updating the milestones could galvanise discussion about how to improve the extension.
#### Proposed Project Timeline:

We should start using Semantic Versioning - the extension offers a few key APIs for contributors to work with (e.g. `BaseConnector`, `Song`, `BaseScrobbler` coming soon...)
- [ ] **v2.0.0** - **_Operation CONSOLIDATE: Standardised. Documented. Tested.**_
  - [x] Port all connectors to 'v2' `Connector` API ( #781 )
  - [ ] Full implementation of v2 API methods, where available:
    - [x] Check album (#576) [50 of 97]
    - [ ] Check current time [20 of 97]
    - [x] Check art (#778) [49 of 97]
    - [ ] Check duration [15 of 97]
    - [ ] Check uniqueid [13 of 97]
  - [ ] Build testing suite:
    - [ ] `/core/` unit tests ( #235 )
    - [ ] `/connectors/` browser testing ( #779 )
  - [ ] Update dev dependencies: ![](https://camo.githubusercontent.com/235f96fea8124ecf76fd00c45af00ffbfb064170/68747470733a2f2f696d672e736869656c64732e696f2f64617669642f6465762f64617669642d7361626174612f7765622d7363726f62626c65722e737667)
  - [ ] Fully document code in `/core/`
  - [ ] Update Github wiki ( #102 )
- [ ] **v2.1.0+** - **_Operation INFORM: Transparent. Intuitive. Convenient.**_
  - [ ] Improve UX for errors:
    - [ ] authorisation errors - catch errors, suggest reauth'ing, make it more reliable, etc. ( #758, #796 )
    - [ ] connector errors - catch errors, suggest refreshes, etc. ( #757 )
  - [ ] Notify users of site-native scrobble functionality
  - [ ] Implement `chrome.storage` ( #647 )
    - [ ] Sync extension settings/authorisation
    - [ ] View/edit scrobble history ( #211, #265, #291 )
  - [ ] More granular options/config
    - [ ] Move popup to `browserAction`, leave `pageAction` for connector-specific options UI (#776)
    - [ ] Clear out notifications ( #467 )
    - [ ] Options for notification info & buttons ( #776 )

**Comment by galeksandrp** [comment]
My thoughts about github: it nice, but it:
- :smile: Does not have option 'Close issue for me', so i wrote [userscritpt that close issue to localStorage](https://gist.github.com/galeksandrp/421a55bdec7b1bb6cd5d).
![image](https://cloud.githubusercontent.com/assets/3586205/9836149/0784b674-5a17-11e5-9c75-d0b6253e77e0.png)

Also ZenHub extension have +1, that could be used for this (and +1 is shared to all extension users!).
- :disappointed: Does not enable label and milestone managing. All kanban-boards with github auth manage labels directly on github (that works only for owners).

**Comment by janbaykara** [comment]
I don't know if we need to worry too much about the way we manage discussion - I think what we really need is to actually do the discussing. I'm definitely a fan of keeping things simple...

**Comment by galeksandrp** [comment]
Well, this topic needs to be marked as `discussion`.

[v2 connectors](https://github.com/galeksandrp/web-scrobbler/branches/all?utf8=%E2%9C%93&query=v2) 
[v2 progress](https://github.com/galeksandrp/web-scrobbler/wiki/v1)

**Comment by janbaykara** [comment]
I wouldn't worry much about Opera, tbh. Cracking work so far though.

Any more thoughts on feature timeline? We can turn agreed 'goals' into individual issues afterwards - as an example, v2 total upgrade could have it's own discussion area.

**Comment by galeksandrp** [comment]
looks like v2 discussion in #731. It not be early merged without any test.
